Weboldal/config/routes.rb
Rails.application.routes.draw do
  post 'sessions/create', to: 'sessions#create', as: 'login'
  get 'sessions/destroy', to: 'sessions#destroy', as: 'logout'

  resources 'images', only: [:index, :new, :show, :destroy] do
    post 'upload', to: 'images#upload', as:'upload', on: :collection
    get 'download', to: 'images#download', as:'download', on: :member
    post 'addtofavourite', to: 'images#addtofavourite', as:'addtofavourite', on: :member
    post 'removefromfavourite', to: 'images#removefromfavourite', as:'removefromfavourite', on: :member
    post 'addcomment', to: 'images#addcomment', as:'addcomment', on: :member
    post 'addtag', to: 'images#addtag', as:'addtag', on: :member
    post 'removetag/:tag_id', to: 'images#removetag', as:'removetag', on: :member
  end

  get 'users/login', to: 'users#login', as: 'loginpage'
  get 'users/new', to: 'users#new', as: 'register'
  post 'users/create', to: 'users#create', as: 'createuser'
  get 'users/forgotten', to: 'users#forgotten', as: 'forgottenpage'
  post 'users/send_forgotten', to: 'users#send_forgotten', as: 'send_forgotten'

  root  to:  'users#login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Weboldal/app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    before_save :encrypt_password

    validates :name, presence: true
    validates :email, {presence: true, uniqueness: true}
    validates :password, confirmation: true, if: :password_required?

    def password_required?
        self.new_record? || !self.password.blank?
    end

    def User.encrypt(password, salt)
        Digest::SHA1.hexdigest(password + salt)
    end

    def encrypt_password
        return if self.password.blank?
        if self.new_record?
            self.salt = SecureRandom.base64  16
        end
        self.encrypted_password = User.encrypt(self.password, self.salt)
    end

    def self.authenticate(email, pass)
        user = User.where(email: email).take
        user && user.authenticated?(pass) ? user : nil
    end

    def authenticated?(pass)
        self.encrypted_password == User.encrypt(pass, self.salt)
    end
end

Weboldal/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    logged_in_checker
  end

  def new
    logged_in_checker
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:user] = 'Sikeres regisztráció!'
      session[:user] = @user.id
      redirect_to images_path
    else
      flash[:user] = @user.errors.messages
      redirect_to  register_path
    end
  end

  def forgotten
    logged_in_checker
  end

  def send_forgotten
  end

  private
  def user_params
    params.require(:user).permit([:name, :email, :password, :password_confirmation])
  end

  def logged_in_checker
    if session[:user]
      redirect_to images_path
    end
  end
end

Weboldal/app/helpers/users_helper.rb
module UsersHelper
end

Weboldal/app/views/users/forgotten.html.erb
<div id="centerForm">
    <fieldset>
        <legend>Add meg az email címed a jelszó helyreállításához</legend>
        <%= form_tag send_forgotten_path, method: :post do %>
            <%= label_tag 'email', 'Email' %>
            <%= text_field 'email', '', placeholder: 'Email' %>

            <%= submit_tag "Jelszó helyreállítása" %>
        <% end %>
    </fieldset>
</div>

Weboldal/app/views/users/login.html.erb
<div id="centerForm">
    <fieldset>
        <legend>Bejelentkezés</legend>
        <%= form_tag login_path, method: :post do %>
            <%= label_tag 'email', 'Email' %>
            <%= text_field 'email', '', placeholder: 'Email' %>

            <%= label_tag 'password', 'Jelszó' %>
            <%= password_field_tag 'password', '', placeholder: 'Jelszó' %>

            <%= submit_tag "Bejelentkezés" %>
        <% end %>
    </fieldset>
</div>

Weboldal/app/views/users/new.html.erb
<div id="centerForm">
    <fieldset>
        <legend>Regisztráció</legend>
        <%= form_for @user, url: createuser_path, method: :post do |form|%>

            <%= form.label :name, 'Név' %>
            <%= form.text_field :name, placeholder: 'Név' %>

            <%= form.label :email, 'Email' %>
            <%= form.text_field :email, placeholder: 'Email' %>

            <%= form.label :password, 'Jelszó' %>
            <%= form.password_field :password, placeholder: 'Jelszó' %>

            <%= form.label :password_confirmation, 'Jelszó megerősítése' %>
            <%= form.password_field :password_confirmation, placeholder: 'Jelszó megerősítése' %>
            
            <%= form.submit "Regisztáció" %>
        <% end %>
    </fieldset>
</div>