Weboldal/config/routes.rb
Rails.application.routes.draw do
  post 'sessions/create', to: 'sessions#create', as: 'login'
  get 'sessions/destroy', to: 'sessions#destroy', as: 'logout'

  resources 'images', only: [:index, :new, :show, :destroy] do
    post 'upload', to: 'images#upload', as:'upload', on: :collection
    get 'download', to: 'images#download', as:'download', on: :member
    post 'addtofavourite', to: 'images#addtofavourite', as:'addtofavourite', on: :member
    post 'removefromfavourite', to: 'images#removefromfavourite', as:'removefromfavourite', on: :member
    post 'addcomment', to: 'images#addcomment', as:'addcomment', on: :member
    post 'addtag', to: 'images#addtag', as:'addtag', on: :member
    post 'removetag/:tag_id', to: 'images#removetag', as:'removetag', on: :member
  end

  get 'users/login', to: 'users#login', as: 'loginpage'
  get 'users/new', to: 'users#new', as: 'register'
  post 'users/create', to: 'users#create', as: 'createuser'
  get 'users/forgotten', to: 'users#forgotten', as: 'forgottenpage'
  post 'users/send_forgotten', to: 'users#send_forgotten', as: 'send_forgotten'

  root  to:  'users#login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Weboldal/app/views/layouts/_guest.html.erb
<%= button_to  "Bejelentkezés", loginpage_path, :method => :get, form_class: "mButtonForm", class:"mButton" %>
<%= button_to  "Regisztáció", register_path, :method => :get, form_class: "mButtonForm", class:"mButton" %>
<%= button_to  "Elfelejtett jelszó", forgottenpage_path, :method => :get, form_class: "mButtonForm", class:"mButton" %>

Weboldal/app/views/layouts/_user.html.erb
<fieldset id = 'userName'>
    <legend><%= @user.name %></legend>
    <%= button_to  "Képek", images_path, :method => :get, form_class: "mButtonForm", class:"mButton" %>
    <%= button_to  "Feltöltés", new_image_path, :method => :get, form_class: "mButtonForm", class:"mButton" %>
    <%= button_to  "Kijelentkezés", logout_path, :method => :get, form_class: "mButtonForm", class:"mButton" %>
</fieldset>

Weboldal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Képmegosztó Weboldal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% flash.each do |type, msg| %>
      <script>
        var str = '<%= raw msg.to_s.delete("\'") %>';
        alert(str);
      </script>
    <% end %>

  </head>

  <body>
    <div id="page">
      <div id="menu">
        <% if logged_in? %>
          <%= render 'layouts/user' %>
        <% else %>
          <%= render 'layouts/guest' %>
        <% end %>
      </div>
      <div id="content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>