Weboldal/config/routes.rb
Rails.application.routes.draw do
  post 'sessions/create', to: 'sessions#create', as: 'login'
  get 'sessions/destroy', to: 'sessions#destroy', as: 'logout'

  resources 'images', only: [:index, :new, :show, :destroy] do
    post 'upload', to: 'images#upload', as:'upload', on: :collection
    get 'download', to: 'images#download', as:'download', on: :member
    post 'addtofavourite', to: 'images#addtofavourite', as:'addtofavourite', on: :member
    post 'removefromfavourite', to: 'images#removefromfavourite', as:'removefromfavourite', on: :member
    post 'addcomment', to: 'images#addcomment', as:'addcomment', on: :member
    post 'addtag', to: 'images#addtag', as:'addtag', on: :member
    post 'removetag/:tag_id', to: 'images#removetag', as:'removetag', on: :member
  end

  get 'users/login', to: 'users#login', as: 'loginpage'
  get 'users/new', to: 'users#new', as: 'register'
  post 'users/create', to: 'users#create', as: 'createuser'
  get 'users/forgotten', to: 'users#forgotten', as: 'forgottenpage'
  post 'users/send_forgotten', to: 'users#send_forgotten', as: 'send_forgotten'

  root  to:  'users#login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Weboldal/app/models/image.rb
class Image < ApplicationRecord
    belongs_to :user
    has_many :Favourite, dependent: :destroy
    has_many :Comment, dependent: :destroy
    has_many :Tag, dependent: :destroy

    def Image.save_file(file, user_id)
        return if file.nil?
        return if !(file.content_type =~ /^image\/(jpeg|pjpeg|gif|png|bmp)$/)
        dir = Rails.root.join('public', 'data')
        unless File.exists? dir
            Dir.mkdir dir
        end

        image = Image.create path: '', mime: file.content_type, user_id: user_id
        path = File.join(dir, image.id.to_s)
        File.open(path, 'wb') do |f| f.write(file.read) end
        image.update path: path
        image
    end

    def Image.get_image_page(page, tag, favourite, own, user_id)
        if tag && tag != ''
            images = Image.joins(:Tag).where(tags: {name: tag})
        else
            images = Image.all
        end
        if own
            images = images.where(user_id: user_id)
        end
        if favourite
            images = images.joins(:Favourite).where(favourites: {user_id: user_id})
        end
        images.order(created_at: :asc).paginate(page: page, per_page: 10)
        
    end
end

Weboldal/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit destroy download addtofavourite removefromfavourite addcomment addtag removetag ]

  def index
    logged_in_checker
    @tag = params[:tag]
    @favourite = params[:favourite]
    @own = params[:own]
    @images = Image.get_image_page(params[:page], @tag, @favourite, @own, @user.id)

  end

  def new
    logged_in_checker
  end

  def show
    logged_in_checker
    @uploaderUser = User.find_by(id: @image.user_id).name;
    @comments = Comment.where(image_id: @image.id).order(updated_at: :asc)
    @tags = Tag.where(image_id: @image.id)
  end

  def upload
    image = Image.save_file(params[:image], @user.id)
    if image == nil
      flash[:notice] = 'Hibás feltöltés. Csak képet lehet feltölteni!'
      redirect_back fallback_location: new_image_path
    else
      flash[:notice] = 'Sikeres feltöltés!'
      redirect_to image;
    end
  end

  def download
    send_file @image.path, type: @image.mime
  end

  def destroy
    if @image.user_id == @user.id
      @image.destroy
      flash[:notice] = 'A kép törölve!'
      redirect_to images_path
    end
  end

  def addtofavourite
    if Favourite.where(user_id: @user.id, image_id: @image.id).count() > 0
      flash[:notice] = 'A kép már hozzá van adva a kedvencekhez!'
      redirect_back fallback_location: @image
      return
    end
    f = Favourite.new
    f.user_id = @user.id
    f.image_id = @image.id
    f.save
    flash[:notice] = 'A kép sikeresen hozzáadva a kedvencekhez!'
    redirect_back fallback_location: @image
  end

  def removefromfavourite
    f = Favourite.find_by(user_id: @user.id, image_id: @image.id)
    f.destroy
    flash[:notice] = 'A kép sikeresen törölve a kedvencekből!'
    redirect_back fallback_location: @image
  end

  def addcomment
    comment = params[:content].first
    if comment == ''
      flash[:notice] = 'A komment nem lehet üres!'
      redirect_back fallback_location: @image
      return
    end
    c = Comment.new
    c.content = comment
    c.user_id = @user.id
    c.image_id = @image.id
    c.save
    flash[:notice] = 'Komment hozzáadva!'
    redirect_back fallback_location: @image
  end

  def addtag
    tag = params[:tag].first
    if tag == ''
      flash[:notice] = 'A cimke nem lehet üres!'
      redirect_back fallback_location: @image
      return
    end
    if Tag.where(name: tag, image_id: @image.id).count() > 0
      flash[:notice] = 'A cimke már hozzá van adva a képhez!'
      redirect_back fallback_location: @image
      return
    end
    t = Tag.new
    t.name = tag
    t.image_id = @image.id
    t.save
    flash[:notice] = 'Cimke hozzáadva!'
    redirect_back fallback_location: @image
  end

  def removetag
    t = Tag.find_by(id: params[:tag_id])
    t.destroy
    flash[:notice] = 'A cimke sikeresen törölve!'
    redirect_back fallback_location: @image
  end

  private
  def logged_in_checker
    if !session[:user]
      redirect_to loginpage_path
    end
  end

  def set_image
    @image = Image.find(params[:id])
  end
end

Weboldal/app/helpers/images_helper.rb
module ImagesHelper
    def isFavourite?(user_id, image_id)
        Favourite.where(user_id: user_id, image_id: image_id).count() > 0
    end

    def uploader(user_id)
        User.find_by(id: user_id).name
    end

    def tagdb(tagName)
        Tag.where(name: tagName).count
    end
end

Weboldal/app/views/images/index.html.erb
<fieldset id="imageFieldset">
    <legend>Keresés</legend>
    <%= form_tag images_path, method: :get do %>
        <%= text_field_tag 'tag', @tag, placeholder: 'Cimke' %>
       
        <%= check_box_tag 'favourite', '', @favourite %>
        <%= label_tag 'favourite', 'Kedvendek' %>
        
        <%= check_box_tag 'own', '', @own %>
        <%= label_tag 'own', 'Saját képek' %>
        
        <%= submit_tag "Keresés", name: "" %>
    <% end %>
</fieldset>

<fieldset id="imageFieldset">
    <legend>Képek</legend>

    <% @images.each do |image| %>
        <div id="imageDiv">
            <a href="<%= image_path(image.id) %>">
                <%= image_tag download_image_path(image.id) %>
            </a>
        </div>
    <% end %>
    <div style="margin: 15px;"><%= will_paginate  @images %></div>
</fieldset>

Weboldal/app/views/images/new.html.erb
<div id="centerForm">
    <fieldset>
        <legend>Kép feltöltése</legend>

        <%= form_tag(upload_images_path, :accept => 'image/*', method: :post, multipart: true) do %>
            <%= label_tag 'Kép' %>
            <%= file_field_tag :image %>
            <%= submit_tag 'Feltöltés' %>
        <% end %>

    </fieldset>
</div>

Weboldal/app/views/images/show.html.erb
<div id="showContentDiv">
    <fieldset>
        <div id="showImageDiv">
            <%= image_tag download_image_path(@image.id) %>
        </div>
        <div id="showImageSettingsDiv">
            <fieldset>
                <legend>Kép tulajdonságai</legend>
                <% if @image.user_id == @user.id %>
                    <%= button_to "Törlés", image_path(@image.id), method: :delete, data: { confirm: 'Biztos ki akarod törölni a képet?' } %>
                <% end %>

                <% if isFavourite?(@user.id, @image.id) %>
                    <%= button_to "Eltávolítás a kedvencekből", removefromfavourite_image_path(@image.id), :method => :post %>
                <% else %>
                    <%= button_to "Kedvencekhez adás", addtofavourite_image_path(@image.id), :method => :post %>
                <% end %>

                <table id="tagTable">
                    <tr>
                      <th>Cimke</th>
                      <th>db</th>
                      <% if @image.user_id == @user.id %>
                        <th>Törlés</th>
                      <% end %>
                    </tr>
                    <% @tags.each do |tag| %>
                        <tr>
                            <td><%= tag.name %></td>
                            <td><%= tagdb tag.name %></td>
                            <% if @image.user_id == @user.id %>
                                <td><%= button_to "X", removetag_image_path(@image.id, tag_id: tag.id), :method => :post %></td>
                            <% end %>
                        </tr>
                    <% end %>
                  </table>

                <% if @image.user_id == @user.id %>
                    <fieldset>
                        <legend>Cimke hozzáadása</legend>
                        <%= form_tag addtag_image_path(@image.id), method: :post do %>
                            <%= text_field 'tag', '', placeholder: 'Cimke' %>
                
                            <%= submit_tag "Hozzáadás" %>
                        <% end %>
                    </fieldset>
                <% end %>
                <p>Feltöltő: <%= @uploaderUser %></p>
            </fieldset>
        </div>
    </fieldset>
</div>

<div id="showCommentDiv">
    <fieldset>
        <legend>Komment hozzáadása</legend>
        <%= form_tag addcomment_image_path(@image.id), method: :post do %>
            <%= text_area 'content', '', placeholder: 'Komment' %>

            <%= submit_tag "Küldés" %>
        <% end %>
    </fieldset>
    <fieldset>
        <legend>Kommentek</legend>
        <% @comments.each do |comment| %>
            <fieldset>
                <legend><%= uploader(comment.user_id) %></legend>
                <%= simple_format comment.content %>
                <p style="text-align:right"><%= comment.updated_at %></p>
            </fieldset>
        <% end %>
    </fieldset>
</div>